spring.application.name=WebSocket-One-to-One-Chat-App


spring.data.mongodb.uri=mongodb://localhost:27017/chat_app


logging.level.org.springframework.web=INFO
logging.level.org.springframework.messaging=INFO
logging.level.org.mongodb.driver=INFO